{"uuid": "a52f14e2-7a4d-4de3-8f5d-e4c8709ff809", "children": ["dd2335fa-d798-4085-849f-4c18bb9f55da", "63dd55d3-60bd-4b67-bd85-8fa586700044", "d72984d5-ff7c-445b-8fea-ff80570e66fd", "d7b45e7a-9cbd-40fb-b0c6-4a906788d854", "a1b5ea0a-ba94-4275-b82d-41a2ad985cfe", "da4cedb3-26e5-46c8-bba7-001a6fa42226", "448c35fe-1ace-4425-bae9-2a920e6302a2", "79446304-1a92-4cb4-ad6a-53292d3149c6", "18ec739e-ed46-4ab7-9dbd-0ffd156344c6", "897a5346-0acb-4b34-bc94-63f1965ee6ed", "08be914a-5110-4055-a2c0-7a8f2e31e3b5", "0ae34299-a1b1-4c76-b9c1-56fd75fd0a86", "0cf1cd9f-3180-46ef-9996-e1379cce205d", "af13a9fe-0f51-454d-a009-51a2cd4fc232", "72218e33-ea74-41db-9040-ed0f13b76958"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom chrome not reachable\n  (Session info: chrome=85.0.4183.102)\n\n", "trace": "  File \"C:\\Users\\yuedan\\AppData\\Roaming\\Python\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\python.py\", line 745, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\python.py\", line 674, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\yundeng_ui\\Scripts\\test_pri.py\", line 16, in setup_class\n    self.driver = driver.get_driver()\n  File \"D:\\yundeng_ui\\Base\\driver.py\", line 3, in get_driver\n    driver = webdriver.Chrome()\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\yuedan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1599817160691, "stop": 1599817176038}], "start": 1599817160691, "stop": 1599817176909}